ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    imu0: /imu/mpu6050
    imu0_config: [false, false, false,  # hata verdi
                  false, false, true,  # degismedi
                  false, false, false,  # hata verdi
                  false, false, true,   # angular velocity x, y, z
                  true, false, false]   # linear acceleration x, y, z
    imu0_differential: false

    odom0: /diffbot_base_controller/odom
    odom0_config: [false, false, false,  # degismedi
                   false, false, true,  # en sondaki değiişince dönüş verisi 
                   true, true, false,    # degismedi
                   false, false, true,   # degismedi
                   false, false, false]  # Ax, Ay, Az (doğrusal ivme)
    odom0_differential: false
    publish_tf: true

