<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_width" value="0.55" />
  <xacro:property name="base_length" value="0.60" />
  <xacro:property name="base_height" value="0.24" />
  <xacro:property name="wheel_len" value="0.030" />
  <xacro:property name="wheel_radius" value="0.055" />
  <xacro:property name="caster_wheel_radius" value="0.055" />

  <xacro:property name="axle_offset" value="0.10" /> 

   <link name="${prefix}base_footprint" />

  <joint name="${prefix}base_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>  
  </joint>
 
  <link name="${prefix}base_link">
    <collision>
      <origin xyz="${base_length/2 - axle_offset} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${base_length/2 - axle_offset} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <xacro:property name="laser_radius" value="0.05"/>
  <xacro:property name="laser_length" value="0.045"/>
  <xacro:property name="laser_origin_z" value="${base_height * 1.1}"/>

  <joint name="${prefix}base_link_to_laser" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}laser"/>
    <origin xyz="${base_length/2 - axle_offset} 0 ${laser_origin_z}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}"/>
      </geometry>
    </collision>
  </link> 

  <joint name="${prefix}left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}left_wheel"/>
    <origin xyz="0 ${base_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
  </joint>

  <link name="${prefix}left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="${prefix}right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}right_wheel"/>
    <origin xyz="0 -${base_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
  </joint>

  <link name="${prefix}right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="${prefix}caster_frontal_wheel_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}caster_frontal_wheel"/>
    <origin xyz="${base_length - axle_offset - caster_wheel_radius} 0 ${-wheel_radius + caster_wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="${prefix}caster_frontal_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>
  </xacro:macro>

</robot>